routes/dashboard.php
<?php

use Illuminate\Http\Request;

Route::name('dashboard.')->prefix('dashboard')->group(function () {
    Auth::routes();
    Route::get('/test',function(){
        $tags = 'hello,test,shampo';
        $tagsArr = explode(',',$tags);
        foreach($tagsArr as $tag)
        {
            dd($tag);
        }
        dd($tagsArr);
    });
    Route::post('/uploadImage', 'ImageController@editorUpload');
    Route::group(['middleware'=>'auth'], function () 
    {
        Route::get('/','HomeController@home')->name('home');
        Route::get('children/{category}','CategoriesController@getChildren')->name('categories.getChildren');
        Route::get('categories/order','CategoriesController@orderIndex')->name('categories.order');
        Route::post('categories/order','CategoriesController@orderSubmit')->name('categories.order.submit');
        Route::resource('categories', 'CategoriesController');
        Route::post('users/confirmDelete','UserController@confirmDelete' )->name('users.confirmDelete');    
        Route::resource('users', 'UserController');
        Route::post('saveAction/{article}','ArticleController@saveArticle')->name('article.saveActions');
        Route::post('articles/addToTrend','ArticleController@addToTrend')->name('article.addToTrend');
        Route::put('articles/verifyArticle/{article}','ArticleController@verify')->name('article.verify');
        Route::resource('article', 'ArticleController');
        Route::delete('trend/{trend}/removeArticle/{article}','TrendController@removeArticle')->name('trend.removeArticle');
        Route::post('trend/removeArticles','TrendController@removeArticles')->name('trend.removeArticles');
        Route::resource('trend', 'TrendController');
        Route::resource('subscribtion', 'SubscribtionsController');        

        Route::get('single', function () {
            return view('dashboard.article.single');
        });
        Route::resource('about', 'AboutController');
    });
});

routes/web.php
<?php

Route::get('/','HomeController@index')->name("home");
Route::get('/search', 'ArticleController@search')->name('search');
Route::get('/articles/', 'ArticleController@search')->name('article.tag');
Route::get('section/{categorySlug}','ArticleController@index')->name('section.single');
Route::get('article/view/{articleSlug}','ArticleController@single')->name('article.single');
Route::get('articles/top-important/{categorySlug?}','ArticleController@mostImportant')->name('article.mostImportant');
Route::get('profile/{id}','HomeController@profile')->name('author.profile');
Route::get('trending/{trendSlug}','ArticleController@trendIndex')->name('trend.index');
Route::post('/subscribe', 'HomeController@subscribe')->name('subscribe');

app/Models/Article.php
<?php

namespace App\Models;

use App\Traits\MakeSlug;
use App\Traits\hasFilter;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Article extends Model implements HasMedia
{
    use HasMediaTrait,hasFilter;

    protected $table = 'articles';
    protected $fillable = ['title','focus_keyword','description','content','author_id','category_id','author_name','verified_by','slug','cover_type','is_infographic','is_news','is_important','in_slider','visits','verified','is_author','created_by'];

    use SoftDeletes,MakeSlug;

    public const COVER_IMAGE = 0;
    public const COVER_VIDEO = 1;
    public const COVER_SLIDER = 2;
    public const READING_SPEED = 200;


    //region functions
    public function getCoverPhotoAttribute()
    {
        $media    = $this->getMedia('article_coll')->first();
        $img      = $media != null ? $media->getFullUrl(): '';
        return $img;
    }

    public function getTagsStringAttribute()
    {
        $tagsArray = $this->tags()->pluck('name')->toArray();
        $tagsString = implode(',',$tagsArray);
        return $tagsString;
    }

    public function getDisplayAuthorNameAttribute()
    {
        return $this->author_name;
    }

    public function refreshSlug()
    {
        $slug = $this->make_slug($this->title).'-'.$this->id;
        $this->update([
            'slug' => $slug,
        ]);
    }

    /**
     * Checks if this belongs to a category
     * @return bool
     */
    public function isMyCategory($category_id)
    {
        if( $this->category_id == $category_id || $this->category->parent_id == $category_id )
        {
            return true;
        }
        else
        {
            return false;
        }
    }

    public function similiarArticles()
    {
        $similiarArticles = Article::whereHas('tags', function ($query) {
            $tagIds = $this->tags()->pluck('tags.id')->all();
            $query->whereIn('tags.id', $tagIds);
        })->where('id', '<>', $this->id)->get();

        return $similiarArticles;
    }

    public function getReadingTimeAttribute()
    {
        $floatMinutes = $this->mb_str_word_count(strip_tags($this->content)) / 200;
        return sprintf('%02d:%02d', (int) $floatMinutes, fmod($floatMinutes, 1) * 60);
    }

    private function mb_str_word_count($string, $format = 0, $charlist = '[]')
    {
        $string=trim($string);
        if(empty($string))
            $words = array();
        else
            $words = preg_split('~[^\p{L}\p{N}\']+~u',$string);
        switch ($format) {
            case 0:
                return count($words);
                break;
            case 1:
            case 2:
                return $words;
                break;
            default:
                return $words;
                break;
        }
    }
    //endregion

    //region Relations
    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function tags()
    {
        return $this->belongsToMany(Tag::class,'article_tags');
    }

    public function author()
    {
        return $this->belongsTo(User::class,'author_id');
    }

    public function createdBy()
    {
        return $this->belongsTo(User::class,'created_by')->withDefault();
    }

    public function roles()
    {
        return $this->belongsToMany('App\Role', 'role_user_table', 'user_id', 'role_id');
    }

    public function trends()
    {
        return $this->belongsToMany(Trend::class, 'article_trends', 'article_id', 'trend_id');
    }
    //endregion

    //region Scopes
    public function scopeSite($query)
    {
        return $query->where('verified',true);
    }

    public function scopeImportant($query)
    {
        return $query->where('is_important',true);
    }

    public function scopeIsAuthor($query)
    {
        return $query->where('is_author',true)->where('author_id','!=',null);
    }

    /**
     * Getting the articles depending on user level
     */
    public function scopeUser($query)
    {
        $user = Auth::user();
        if($user->hasRole(User::AUTHOR_ROLE))
            return $query->where('author_id',$user->id);
        else
            return $query;
    }
    //endregion

}

app/Models/Trend.php
<?php

namespace App\Models;

use App\Traits\MakeSlug;
use Illuminate\Database\Eloquent\Model;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Illuminate\Database\Eloquent\SoftDeletes;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;

class Trend extends Model implements HasMedia
{
    use SoftDeletes,HasMediaTrait,MakeSlug;

    protected $table = 'trends';
    protected $fillable = ['name','slug'];
    const COVER_IMAGE_MEDIA_COLLECTION = 'cover';
    
    public function articles()
    {
        return $this->belongsToMany(Article::class,'trend_articles','trend_id','article_id');
    }

    public function updateCoverImage($image)
    {
        foreach($this->getMedia(self::COVER_IMAGE_MEDIA_COLLECTION) as $image)
        {
            $image->delete();
        }
        $this->addMedia($image)->toMediaCollection(self::COVER_IMAGE_MEDIA_COLLECTION);
    }

    public function getCoverImageUrlAttribute()
    {
        $coverImages = $this->getMedia(self::COVER_IMAGE_MEDIA_COLLECTION);

        $coverImageUrl = $coverImages->first()? $coverImages->first()->getFullUrl() : null;    
        return $coverImageUrl;
    }

    public function getUrl()
    {
        $articles = $this->articles();
        if($articles->count()>1)
        {
            return route('trend.index',$this->slug??$this->id);
        }
        else
        {
            return route('article.single',$articles->first()->slug);
        }
    }

    public function refreshSlug()
    {
        $slug = $this->make_slug($this->name).'-'.$this->id;
        $this->update([
            'slug' => $slug,
        ]);
    }

    public function scopeHasArticles($query)
    {
        return $query->whereHas('articles');
    }
}

app/Http/Controllers/Dashboard/AboutController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Statics;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.about.about');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Statics::updateStatics($request->except('_token'));

        return back()->withSuccess('Success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/ArticleController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use App\Models\ArticleTag;
use App\Models\Author;
use App\Models\Category;
use App\Models\Tag;
use App\Models\Trend;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
class ArticleController extends Controller
{
    public function __construct()
    {

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $articles = Article::user()->paginate(10);
        $trends = Trend::all();
        return view('dashboard.article.index',compact('articles','trends'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $article    = new Article();
        $categories = Category::parents()->get();
        $authors    = User::all();
        $img = null;
        return view('dashboard.article.form',compact('categories','authors','article','img'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        $requestData = $request->all();

        if(!Auth::user()->hasRole(User::AUTHOR_ROLE))
        {
            $requestData['verified']    = true;
            $requestData['verified_by'] = Auth::user()->id;
        }

        $requestData['created_by'] = Auth::user()->id;

        if(isset($requestData['sub_category_id']))
        {
            $requestData['category_id'] = $requestData['sub_category_id'];
        }
        $article   = Article::create($requestData);
        if($request->hasFile('article_image'))
        {
            $article->addMedia($request->article_image)
            ->toMediaCollection('article_coll');
        }

        $tags      = $request->tags;
        $splitTags = explode(',',$tags);
        foreach($splitTags as  $splitTag )
        {
            $tagsTable = Tag::where('name',$splitTag)->first();
            if($tagsTable == null)
            {
                $tagsTable        = new Tag();
                $tagsTable->name  = $splitTag;
                $tagsTable->save();
            }

            $tagsArticleTable             = new ArticleTag();
            $tagsArticleTable->article_id = $article->id;
            $tagsArticleTable->tag_id     = $tagsTable->id;
            $tagsArticleTable->save();
        }
        $article->refreshSlug();

        if ($article->save())
        {
            \SEO\Seo::save($article, route('article.single', $article->slug), [
                    'title' => $article->title,
                    'images' => [
                    $article->cover_photo
                ]
            ]);
        }
        return redirect()->route('dashboard.article.index')->withSuccess('Success','تمت الاضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        return view('dashboard.article.single',compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        $categories = Category::parents()->get();
        $authors    = User::all();
        $media      = $article->getMedia('article_coll')->first();
        $img        = $media ? $media->getFullUrl() : '';
        $tags       = ArticleTag::where('article_id',$article->id)->get();
        return view('dashboard.article.form',compact('categories','authors','article','img','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, Article $article)
    {
        $requestData = $request->all();

        if(isset($requestData['sub_category_id']))
        {
            $requestData['category_id'] = $requestData['sub_category_id'];
        }

        $article->update($requestData);

        if($request->article_image != null)
        {
            $article->addMedia($request->article_image)
                    ->toMediaCollection('article_coll');
        }
        $article->refreshSlug();

        if ($article->save())
        {
            \SEO\Seo::save($article, route('article.single', $article->slug), [
                    'title' => $article->title,
                    'images' => [
                    $article->cover_photo
                ]
            ]);
       }
        return redirect()->route('dashboard.article.index')->withSuccess('Success','تمت التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->route('dashboard.article.index')->withSuccess('تم حذف المقال بنجاح');
    }

    public function saveArticle(Request $request,$article)
    {
        $article = Article::find($article);
        $article->update
            ([
                'is_news'=> $request->is_news,
                'is_important'=> $request->is_important ,
                'in_slider'=> $request->is_slider ,
                'is_infographic'=> $request->is_infographic,
                'is_author' => $request->is_author
            ]);
        return back()->withSuccess('تم التعديل بنجاح');
    }

    public function addToTrend(Request $request)
    {
        $trend = Trend::find($request->trend_id);
        $articles = $request->articles;
        $trend->articles()->attach($articles);
        return response()->json(['message'=>'تم اضافة المقالات الى الترند بنجاح']);
    }

    public function verify(Article $article)
    {
        $article->update([
            'verified'=>true,
            'verified_by'=> Auth::user()->id
        ]);
        return back()->withSuccess('تم الموافقة على المقالة بنجاح');
    }

}

app/Http/Controllers/Dashboard/ImageController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ImageController extends Controller
{
    public function editorUpload(Request $request)
    {
        $file = $request->upload->store('/public');
        $fileUrl = Storage::url($file);
        $fileName = basename($file);
        $response = [
            'fileName' => $fileName,
            'uploaded' => 1,
            'url' => $fileUrl,
        ];
        return response()->json($response);
    }
}

resources/views/dashboard/trend/form.blade.php
@extends('dashboard.layouts.main')
@section('content')
    <div class="content">
        <!-- START JUMBOTRON -->
        <div class="jumbotron" data-pages="parallax">
            <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
                <div class="inner">
                    <!-- START BREADCRUMB -->
                    <ul class="breadcrumb">
                        <li>
                            <p>التريندات</p>
                        </li>
                        <li><a href="#" class="active">اضافة تريند</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- END JUMBOTRON -->

        <!-- START CONTAINER FLUID -->
        <div class="container-fluid container-fixed-lg">
            <!-- START PANEL -->
            <div class="panel panel-default">
                <div class="panel-heading" data-id="achievTab">
                    <div class="panel-title">
                        @if ($trend->id)
                        تعديل تريند
                        @else
                        اضافة تريند
                        @endif
                    </div>
                </div>
                <div class="panel-body" id="achievTab">
                    <!-- <h5>
                        Home Picture
                    </h5> -->
                    @if ($errors->any())
                        <p>Errors</p>
                        @foreach ($errors->all() as $error)
                            <p>{{$error}}</p>
                        @endforeach
                    @endif
                    <form class="form" role="form" action="{{isset($trend->id) ? route('dashboard.trend.update',$trend->id) : route('dashboard.trend.store')}}" enctype="multipart/form-data" method="POST">
                        @csrf
                        @isset($trend->id)
                            @method('PUT')
                        @endisset
                        <div class="row">
                            <div class="col-sm-12 col-12">
                                <div class="form-group">
                                    <label>الاسم &nbsp; </label>
                                    <span class="help"></span>
                                    <input type="text"  class="form-control" value="{{$trend->name}}" name="name" required>
                                </div>
                            </div>
                            <div class="col-sm-12 col-12">
                                <div class="form-group">
                                    <label>صورة التريند</label>
                                    <input name="image" class="form-control" id="myId" type="file" multiple />
                                    @if($trend->cover_image_url)
                                    <img src="{{$trend->cover_image_url}}" style="width: 50px; height: 50px; object-fit: contain;" />
                                    @endif
                                </div>
                            </div>
                        </div>

                        <div class="pull-right">
                            <button class="btn btn-primary btn-cons">حفظ</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- END PANEL -->
        </div>

    </div>

@endsection
@section('javascript')
@include('dashboard.layouts.form_scripts')
@include('dashboard.layouts.sweetalert')
@endsection

resources/views/dashboard/trend/index.blade.php
@extends('dashboard.layouts.main')
@section('content')
<div class="content">
    <!-- START JUMBOTRON -->
    <div class="jumbotron" data-pages="parallax">
        <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
            <div class="inner">
                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li>
                        <p>التريندات</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->

    <!-- START CONTAINER FLUID -->
    <div class="container-fluid container-fixed-lg bg-white">
        <div class="panel panel-transparent">
            <div class="panel-heading">
                <div class="panel-title">التريندات</div>
                <div class="export-options-container pull-right"></div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <table class="table table-striped" >
                    <thead>
                        <tr>
                            <th>اسم التريند</th>
                            <th>عدد المقالات</th>
                            <th>الصورة</th>
                            <th>خيارات</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($trends as $trend)
                        <tr class="odd gradeX">
                            <td>{{$trend->name}}</td>
                            <td>{{$trend->articles()->count()}}</td>
                            <td>
                                @if ($trend->cover_image_url)
                                    <img src="{{$trend->cover_image_url}}" style="width: 100px;height: 100px">
                                    
                                @endif
                            </td>
                            <td class="ceneter">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                          خيارات <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a href="{{route('dashboard.trend.edit',$trend->id)}}">تعديل</a>
                                        </li>
                                        <li>
                                            <a href="{{route('dashboard.trend.show',$trend->id)}}">عرض</a>
                                        </li>
                                        <li>
                                            <form action="{{route('dashboard.trend.destroy',$trend->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-primary">حذف</button>
                                            </form>
                                        </li>
                                        
                                    </ul>
                                </li>
                            </td>
                           
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{$trends->links()}}
            </div>
        </div>
    </div>
    <!-- END CONTAINER FLUID -->
    <br><br>

</div>
@endsection

resources/views/dashboard/trend/single.blade.php
@extends('dashboard.layouts.main')
@section('content')
<div class="content">

  <!-- START JUMBOTRON -->
  <div class="jumbotron" data-pages="parallax">
    <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
        <div class="inner">
            <!-- START BREADCRUMB -->
            <ul class="breadcrumb">
                <li>
                    <p>مقالات تيرند : {{$trend->name}} </p>
                </li>
                {{-- <li><a href="#" class="active">Article View</a></li> --}}
            </ul>
        </div>
    </div>
  </div>
  <!-- END JUMBOTRON -->
   <!-- START CONTAINER FLUID -->
  <div class="container-fluid container-fixed-lg">
    <div class="row">
      <div class="col-md-12">
        <div class="sm-m-l-5 sm-m-r-5">
          <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
            {{-- <div class="panel panel-default">
              <div class="panel-heading" role="tab" id="headingTwo">
                <h4 class="panel-title">
                  <a class="collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    اضافة الى تريند
                  </a>
                </h4>
              </div>
              <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
                <div class="panel-body">
                  <div class="row">
                    <div class="col-sm-8">
                      <div class="form-group">
                        <label>اختر التريند</label>
                        <select class="full-width" id="trands" data-init-plugin="select2">
                          <option value="test">test</option>
                          @foreach ($trends as $trend)
                            <option value="{{$trend->id}}">{{$trend->name}}</option>
                          @endforeach
                        </select>
                      </div>
                    </div>
                    <div class="col-4 text-right">
                      <button class="btn btn-success btn-cons" id="addToTrendButton">اضافة الى تريند</button>
                    </div>
                  </div>
                </div>
              </div>
            </div> --}}
          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- END CONTAINER FLUID -->
  <!-- START CONTAINER FLUID -->
  <div class="container-fluid container-fixed-lg bg-white">
    <div class="panel panel-transparent">
      <div class="panel-heading">
        <div class="panel-title">مقالات تيرند : {{$trend->name}}</div>
        <div class="pull-right">
          <div class="col-xs-12">
            <input type="text" id="search-table" class="form-control pull-right" placeholder="بحث">
          </div>
        </div>
        <div class="clearfix">
          <p> </p>
        </div>
      </div>
      <div class="panel-body">
        <table class="table table-hover demo-table-search" id="tableWithSearch">
          <thead>
            <tr>
              <th></th>
              <th>عنوان المقال </th>
              <th>القسم</th>
              <th>الكاتب</th>
              <th>عدد الزيارات</th>
              {{-- <th>المقال</th> --}}
              <th>الفيديو/الصوره</th>
              <th>خيارات</th>
            </tr>
          </thead> 
          <tbody>
              @foreach ($trendArticles as $article)
            <tr>
              <td>
                <div class="checkbox ">
                  <input type="checkbox" value="{{$article->id}}" id="checkbox1">
                  <label for="checkbox1"></label>
                </div>
              </td>
              <td class="v-align-middle">{{$article->title}}</td>
              <td class="v-align-middle">{{$article->category->name}}</td>
              <td class="v-align-middle">{{$article->author ? $author->name : $article->author_name}}</td>
              <td class="v-align-middle">{{$article->visits}} </td>
              {{-- <td class="v-align-middle">{!!substr($article->content,0,700)!!}</td> --}}
              <td class="v-align-middle">
                <img src="{{$article->cover_photo}}" style="width: 150px;height: 100px" />
              </td>
              <td class="v-align-middle">
                <li class="dropdown">
                  <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                      خيارات <span class="caret"></span>
                  </a>
                  <ul class="dropdown-menu" role="menu">
                      <li>
                        <a href="{{route('dashboard.article.show',$article->id)}}">عرض</a>
                      </li>
                      <li>
                          <a href="{{route('dashboard.article.edit',$article->id)}}">تعديل</a>
                      </li>
                      <li>
                          <form action="{{route('dashboard.trend.removeArticle',['trend'=>$trend->id,'article'=>$article->id])}}" method="post">
                              @csrf
                              @method('DELETE')
                              <button class="btn btn-primary">حذف من التريند</button>
                          </form>
                      </li>
                      <li>
                      </li>
                  </ul>
                </li>
              </td>
            </tr>
            @endforeach
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <!-- END CONTAINER FLUID -->
  <br><br>
</div>
@endsection

@section('javascript')
<script>
    var articleCheckboxsValues = [];
    $('#addToTrendButton').on('click', function() {
        var trendId = $('#trands').val();
        // console.log('checkbox values: ', articleCheckboxsValues, 'trand name', trandName);
        if (articleCheckboxsValues.length == 0) 
        {
            alert('Must Choose Article From Table');
        }
        else
        {
            $.post('{{route("dashboard.article.addToTrend")}}',{
                _token : '{{csrf_token()}}',
                trend_id : trendId,
                articles : articleCheckboxsValues
            },function(data){
                console.log('done');
                swal({
                  title: 'تم بنجاح',
                  html: data.message,
                  type: 'success'
                })
            });  
        }
    });

    $('#tableWithSearch input[type="checkbox"]').on('change', function() {
        if($(this).is(':checked')) {
            articleCheckboxsValues.push($(this).val())
        } else {
            articleCheckboxsValues.splice(articleCheckboxsValues.indexOf($(this).val()), 1);
        }
    });
</script>
@endsection