routes/dashboard.php
<?php

use Illuminate\Http\Request;

Route::name('dashboard.')->prefix('dashboard')->group(function () {
    Auth::routes();
    Route::get('/test',function(){
        $tags = 'hello,test,shampo';
        $tagsArr = explode(',',$tags);
        foreach($tagsArr as $tag)
        {
            dd($tag);
        }
        dd($tagsArr);
    });
    Route::post('/uploadImage', 'ImageController@editorUpload');
    Route::group(['middleware'=>'auth'], function () 
    {
        Route::get('/','HomeController@home')->name('home');
        Route::get('children/{category}','CategoriesController@getChildren')->name('categories.getChildren');
        Route::get('categories/order','CategoriesController@orderIndex')->name('categories.order');
        Route::post('categories/order','CategoriesController@orderSubmit')->name('categories.order.submit');
        Route::resource('categories', 'CategoriesController');
        Route::post('users/confirmDelete','UserController@confirmDelete' )->name('users.confirmDelete');    
        Route::resource('users', 'UserController');
        Route::post('saveAction/{article}','ArticleController@saveArticle')->name('article.saveActions');
        Route::post('articles/addToTrend','ArticleController@addToTrend')->name('article.addToTrend');
        Route::put('articles/verifyArticle/{article}','ArticleController@verify')->name('article.verify');
        Route::resource('article', 'ArticleController');
        Route::delete('trend/{trend}/removeArticle/{article}','TrendController@removeArticle')->name('trend.removeArticle');
        Route::post('trend/removeArticles','TrendController@removeArticles')->name('trend.removeArticles');
        Route::resource('trend', 'TrendController');
        Route::resource('subscribtion', 'SubscribtionsController');        

        Route::get('single', function () {
            return view('dashboard.article.single');
        });
        Route::resource('about', 'AboutController');
    });
});

routes/web.php
<?php

Route::get('/','HomeController@index')->name("home");
Route::get('/search', 'ArticleController@search')->name('search');
Route::get('/articles/', 'ArticleController@search')->name('article.tag');
Route::get('section/{categorySlug}','ArticleController@index')->name('section.single');
Route::get('article/view/{articleSlug}','ArticleController@single')->name('article.single');
Route::get('articles/top-important/{categorySlug?}','ArticleController@mostImportant')->name('article.mostImportant');
Route::get('profile/{id}','HomeController@profile')->name('author.profile');
Route::get('trending/{trendSlug}','ArticleController@trendIndex')->name('trend.index');
Route::post('/subscribe', 'HomeController@subscribe')->name('subscribe');

app/Http/Controllers/Dashboard/AboutController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Statics;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.about.about');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Statics::updateStatics($request->except('_token'));

        return back()->withSuccess('Success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/ArticleController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use App\Models\ArticleTag;
use App\Models\Author;
use App\Models\Category;
use App\Models\Tag;
use App\Models\Trend;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
class ArticleController extends Controller
{
    public function __construct()
    {

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $articles = Article::user()->paginate(10);
        $trends = Trend::all();
        return view('dashboard.article.index',compact('articles','trends'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $article    = new Article();
        $categories = Category::parents()->get();
        $authors    = User::all();
        $img = null;
        return view('dashboard.article.form',compact('categories','authors','article','img'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        $requestData = $request->all();

        if(!Auth::user()->hasRole(User::AUTHOR_ROLE))
        {
            $requestData['verified']    = true;
            $requestData['verified_by'] = Auth::user()->id;
        }

        $requestData['created_by'] = Auth::user()->id;

        if(isset($requestData['sub_category_id']))
        {
            $requestData['category_id'] = $requestData['sub_category_id'];
        }
        $article   = Article::create($requestData);
        if($request->hasFile('article_image'))
        {
            $article->addMedia($request->article_image)
            ->toMediaCollection('article_coll');
        }

        $tags      = $request->tags;
        $splitTags = explode(',',$tags);
        foreach($splitTags as  $splitTag )
        {
            $tagsTable = Tag::where('name',$splitTag)->first();
            if($tagsTable == null)
            {
                $tagsTable        = new Tag();
                $tagsTable->name  = $splitTag;
                $tagsTable->save();
            }

            $tagsArticleTable             = new ArticleTag();
            $tagsArticleTable->article_id = $article->id;
            $tagsArticleTable->tag_id     = $tagsTable->id;
            $tagsArticleTable->save();
        }
        $article->refreshSlug();

        if ($article->save())
        {
            \SEO\Seo::save($article, route('article.single', $article->slug), [
                    'title' => $article->title,
                    'images' => [
                    $article->cover_photo
                ]
            ]);
        }
        return redirect()->route('dashboard.article.index')->withSuccess('Success','تمت الاضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        return view('dashboard.article.single',compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        $categories = Category::parents()->get();
        $authors    = User::all();
        $media      = $article->getMedia('article_coll')->first();
        $img        = $media ? $media->getFullUrl() : '';
        $tags       = ArticleTag::where('article_id',$article->id)->get();
        return view('dashboard.article.form',compact('categories','authors','article','img','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, Article $article)
    {
        $requestData = $request->all();

        if(isset($requestData['sub_category_id']))
        {
            $requestData['category_id'] = $requestData['sub_category_id'];
        }

        $article->update($requestData);

        if($request->article_image != null)
        {
            $article->addMedia($request->article_image)
                    ->toMediaCollection('article_coll');
        }
        $article->refreshSlug();

        if ($article->save())
        {
            \SEO\Seo::save($article, route('article.single', $article->slug), [
                    'title' => $article->title,
                    'images' => [
                    $article->cover_photo
                ]
            ]);
       }
        return redirect()->route('dashboard.article.index')->withSuccess('Success','تمت التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->route('dashboard.article.index')->withSuccess('تم حذف المقال بنجاح');
    }

    public function saveArticle(Request $request,$article)
    {
        $article = Article::find($article);
        $article->update
            ([
                'is_news'=> $request->is_news,
                'is_important'=> $request->is_important ,
                'in_slider'=> $request->is_slider ,
                'is_infographic'=> $request->is_infographic,
                'is_author' => $request->is_author
            ]);
        return back()->withSuccess('تم التعديل بنجاح');
    }

    public function addToTrend(Request $request)
    {
        $trend = Trend::find($request->trend_id);
        $articles = $request->articles;
        $trend->articles()->attach($articles);
        return response()->json(['message'=>'تم اضافة المقالات الى الترند بنجاح']);
    }

    public function verify(Article $article)
    {
        $article->update([
            'verified'=>true,
            'verified_by'=> Auth::user()->id
        ]);
        return back()->withSuccess('تم الموافقة على المقالة بنجاح');
    }

}

app/Http/Controllers/Dashboard/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    public function __construct()
    {
        $this->middleware(['role:Super Admin']);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(20);
        return view('dashboard.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parentCategories = Category::parents()->get();
        $category = new Category();
        return view('dashboard.categories.form',compact('parentCategories','category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $category = Category::create($request->all());
        $category->refreshSlug();
        return redirect()->route('dashboard.categories.index')->withSuccess('Success','تمت اضافة القسم بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $parentCategories = Category::parents()->get();
        return view('dashboard.categories.form',compact('category','parentCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request,Category $category)
    {
        $category->update($request->all());
        $category->refreshSlug();
        return back()->withSuccess('تم تعديل القسم بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Category  $cateogry
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return back()->withSuccess('تم الحذف بنجاح');
    }

    public function getChildren(Category $category)
    {
        if($category->children()->count())
        {
            $children = $category->children;
            return response()->json($children);
        }
        else
        {
            return 'false';
        }
    }

    public function orderIndex()
    {
        $homeCategories = Category::where('in_homepage',1)->orderBy('homepage_order','ASC')->get();
        $notHomeCategories = Category::where('in_homepage',0)->get();
        return view('dashboard.categories.order-categories',compact('homeCategories','notHomeCategories'));
    }

    public function orderSubmit(Request $request)
    {
        $sortingArr = $request->sortingArr;
        Category::query()->update([
            "in_homepage" => 0
        ]);
        foreach ($sortingArr as $index => $category_id) 
        {
            $category = Category::find($category_id);

            $category->update([
                "in_homepage"=>'1',
                "homepage_order"=>$index
            ]);    
        }

        return "success";
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Article;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Sarfraznawaz2005\VisitLog\Models\VisitLog;

class HomeController extends Controller
{
    /**
     * Return Dashboard Homepage
     */
    public function home(Request $request)
    {
        $articlesCount = Article::count();
        $unVerifiedAriclesCount = Article::where('verified',false)->count();
        $topTenArticles = Article::orderBy('visits','desc')->take(10)->get(); 
        $lastMonthVisits = VisitLog::where('created_at','>=',Carbon::now()->subMonth()->firstOfMonth())->count();
        $monthVisits = VisitLog::where('created_at','>=',Carbon::now()->firstOfMonth())->count();
        $chartDaysVisits = $this->getDaysVisitsArray(7);
        // dd($chartDaysVisits); 
        return view('dashboard.home',compact(
            'articlesCount',
            'unVerifiedAriclesCount',
            'lastMonthVisits',
            'monthVisits',
            'chartDaysVisits',
            'topTenArticles'
        ));
    }

    public function getDaysVisitsArray($daysNum)
    {
        $date = Carbon::now()->subDays($daysNum);

        $days = array();
        $daysLabels = array();
        $visits = array();
        for($i=0 ; $i<$daysNum+1 ; $i++)
        {
            array_push($daysLabels,$date->format('M-d'));
            // $dayVisitors = VisitLog::whereBetween('created_at',[$date->toDateTimeString(),$date->addDay()->toDayDateTimeString()])->count();
            $dayVisitors = VisitLog::whereDate('created_at',$date)->count();
            $date->addDay();
            array_push($days,$i+1);
            array_push($visits,$dayVisitors);
        }
        $days = json_encode($days);
        // dd(Carbon::now()->toDateTimeString());
        // dd(VisitLog::whereDate('created_at',Carbon::now())->count());
        $visits = json_encode($visits);
        // $visitsCount = VisitLog::count();
        $daysLabels = json_encode($daysLabels);

        return [
            'days' => $daysLabels,
            'visits' => $visits
        ];
    }
}

app/Http/Controllers/Dashboard/ImageController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ImageController extends Controller
{
    public function editorUpload(Request $request)
    {
        $file = $request->upload->store('/public');
        $fileUrl = Storage::url($file);
        $fileName = basename($file);
        $response = [
            'fileName' => $fileName,
            'uploaded' => 1,
            'url' => $fileUrl,
        ];
        return response()->json($response);
    }
}

resources/views/dashboard/categories/form.blade.php
@extends('dashboard.layouts.main')
@section('content')
    <div class="content">
        <!-- START JUMBOTRON -->
        <div class="jumbotron" data-pages="parallax">
            <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
                <div class="inner">
                    <!-- START BREADCRUMB -->
                    <ul class="breadcrumb">
                        <li>
                            <p>الاقسام</p>
                        </li>
                        <li><a href="#" class="active">اضافة قسم</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <!-- END JUMBOTRON -->

        <!-- START CONTAINER FLUID -->
        <div class="container-fluid container-fixed-lg">
            <!-- START PANEL -->
            <div class="panel panel-default">
                <div class="panel-heading" data-id="achievTab">
                    <div class="panel-title">
                        @if ($category->id)
                        تعديل قسم
                        @else
                        اضافة قسم
                        @endif
                    </div>
                </div>
                <div class="panel-body" id="achievTab">
                    <!-- <h5>
                        Home Picture
                    </h5> -->
                    @if ($errors->any())
                        <p>Errors</p>
                        @foreach ($errors->all() as $error)
                            <p>{{$error}}</p>
                        @endforeach
                    @endif
                    <form class="form" role="form" action="{{isset($category->id) ? route('dashboard.categories.update',$category->id) : route('dashboard.categories.store')}}" enctype="multipart/form-data" method="POST">
                        @csrf
                        @isset($category->id)
                            @method('PUT')
                        @endisset
                        <div class="row">
                            <div class="col-sm-12 col-12">
                                <div class="form-group">
                                    <label>الاسم &nbsp; </label>
                                    <span class="help"></span>
                                    <input type="text"  class="form-control" value="{{$category->name}}" name="name" required>
                                </div>
                            </div>

                            <div class="col-sm-12 col-12">
                                <div class="form-group">
                                    <label>القسم الرئيسى للقسم &nbsp; </label>
                                    <select name="parent_id" class="form-control" id="role_select">
                                        <option value="" disabled selected>اختر القسم</option>
                                        @foreach ($parentCategories as $parentCategory)
                                            <option {{$category->parent_id == $parentCategory ? 'selected' : ''}} value="{{$parentCategory->id}}">{{$parentCategory->name}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            {{-- <div class="col-sm-12 col-12">
                                <div class="form-group">
                                    <label>وصف المدرب &nbsp; </label>
                                    <span class="help"></span>
                                    <textarea class="form-control"  rows="10" name="description" required></textarea>
                                </div>
                            </div>

                            <div class="col-sm-12 col-12">
                                <div class="form-group">
                                    <label> مدرب خاص &nbsp; </label>
                                    <span class="help"></span>
                                    <textarea class="form-control"  rows="10" name="card_text" required></textarea>
                                </div>
                            </div>

                            <div class="col-sm-12 col-12">
                                <div class="form-group">
                                    <label>الفيديو &nbsp; </label>
                                    <span class="help"></span>
                                    
                                    <input type="file" class="form-control" name="video">
                                </div>
                            </div> --}}
                            {{-- <div class="col-sm-12 col-12">
                                <div class="form-group">
                                    <label> الصورة الشخصية &nbsp; </label>
                                    <span class="help"></span>
                                    <input type="file" class="form-control" name="image">
                                </div>
                            </div> --}}
                        </div>

                        <div class="pull-right">
                            <button class="btn btn-primary btn-cons">حفظ</button>
                        </div>
                    </form>
                </div>
            </div>
            <!-- END PANEL -->
        </div>

    </div>

@endsection
@section('javascript')
@include('dashboard.layouts.form_scripts')
@include('dashboard.layouts.sweetalert')
@endsection

resources/views/dashboard/categories/index.blade.php
@extends('dashboard.layouts.main')
@section('content')
<div class="content">
    <!-- START JUMBOTRON -->
    <div class="jumbotron" data-pages="parallax">
        <div class="container-fluid container-fixed-lg sm-p-l-20 sm-p-r-20">
            <div class="inner">
                <!-- START BREADCRUMB -->
                <ul class="breadcrumb">
                    <li>
                        <p>الاقسام</p>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <!-- END JUMBOTRON -->

    <!-- START CONTAINER FLUID -->
    <div class="container-fluid container-fixed-lg bg-white">
        <div class="panel panel-transparent">
            <div class="panel-heading">
                <div class="panel-title">الاقسام</div>
                <div class="export-options-container pull-right"></div>
                <div class="clearfix"></div>
            </div>
            <div class="panel-body">
                <table class="table table-striped" >
                    <thead>
                        <tr>
                            <th> اسم القسم</th>
                            <th>القسم الرئيسى</th>
                            <th>عدد المقالات</th>
                            <th>خيارات</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($categories as $category)
                        <tr class="odd gradeX">
                            <td>{{$category->name}}</td>
                            <td>{{$category->parent->name}}</td>
                            <td>{{$category->articles()->count()}}</td>
                            <td class="ceneter">
                                <li class="dropdown">
                                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                          خيارات <span class="caret"></span>
                                    </a>
                                    <ul class="dropdown-menu" role="menu">
                                        <li>
                                            <a href="{{route('dashboard.categories.edit',$category->id)}}">تعديل</a>
                                        </li>
                                        <li>
                                            <form action="{{route('dashboard.categories.destroy',$category->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <button class="btn btn-primary">حذف</button>
                                            </form>
                                        </li>
                                        
                                    </ul>
                                </li>
                            </td>
                           
                        </tr>
                        @endforeach
                    </tbody>
                </table>
                {{$categories->links()}}
            </div>
        </div>
    </div>
    <!-- END CONTAINER FLUID -->
    <br><br>

</div>
@endsection