routes/dashboard.php
<?php

use Illuminate\Http\Request;

Route::name('dashboard.')->prefix('dashboard')->group(function () {
    Auth::routes();
    Route::get('/test',function(){
        $tags = 'hello,test,shampo';
        $tagsArr = explode(',',$tags);
        foreach($tagsArr as $tag)
        {
            dd($tag);
        }
        dd($tagsArr);
    });
    Route::post('/uploadImage', 'ImageController@editorUpload');
    Route::group(['middleware'=>'auth'], function () 
    {
        Route::get('/','HomeController@home')->name('home');
        Route::get('children/{category}','CategoriesController@getChildren')->name('categories.getChildren');
        Route::get('categories/order','CategoriesController@orderIndex')->name('categories.order');
        Route::post('categories/order','CategoriesController@orderSubmit')->name('categories.order.submit');
        Route::resource('categories', 'CategoriesController');
        Route::post('users/confirmDelete','UserController@confirmDelete' )->name('users.confirmDelete');    
        Route::resource('users', 'UserController');
        Route::post('saveAction/{article}','ArticleController@saveArticle')->name('article.saveActions');
        Route::post('articles/addToTrend','ArticleController@addToTrend')->name('article.addToTrend');
        Route::put('articles/verifyArticle/{article}','ArticleController@verify')->name('article.verify');
        Route::resource('article', 'ArticleController');
        Route::delete('trend/{trend}/removeArticle/{article}','TrendController@removeArticle')->name('trend.removeArticle');
        Route::post('trend/removeArticles','TrendController@removeArticles')->name('trend.removeArticles');
        Route::resource('trend', 'TrendController');
        Route::resource('subscribtion', 'SubscribtionsController');        

        Route::get('single', function () {
            return view('dashboard.article.single');
        });
        Route::resource('about', 'AboutController');
    });
});

routes/web.php
<?php

Route::get('/','HomeController@index')->name("home");
Route::get('/search', 'ArticleController@search')->name('search');
Route::get('/articles/', 'ArticleController@search')->name('article.tag');
Route::get('section/{categorySlug}','ArticleController@index')->name('section.single');
Route::get('article/view/{articleSlug}','ArticleController@single')->name('article.single');
Route::get('articles/top-important/{categorySlug?}','ArticleController@mostImportant')->name('article.mostImportant');
Route::get('profile/{id}','HomeController@profile')->name('author.profile');
Route::get('trending/{trendSlug}','ArticleController@trendIndex')->name('trend.index');
Route::post('/subscribe', 'HomeController@subscribe')->name('subscribe');

app/Http/Controllers/Dashboard/AboutController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Models\Statics;
use Illuminate\Http\Request;

class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('dashboard.about.about');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        Statics::updateStatics($request->except('_token'));

        return back()->withSuccess('Success');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

app/Http/Controllers/Dashboard/ArticleController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\ArticleRequest;
use App\Models\Article;
use App\Models\ArticleTag;
use App\Models\Author;
use App\Models\Category;
use App\Models\Tag;
use App\Models\Trend;
use App\Models\User;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
class ArticleController extends Controller
{
    public function __construct()
    {

    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    public function index()
    {
        $articles = Article::user()->paginate(10);
        $trends = Trend::all();
        return view('dashboard.article.index',compact('articles','trends'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $article    = new Article();
        $categories = Category::parents()->get();
        $authors    = User::all();
        $img = null;
        return view('dashboard.article.form',compact('categories','authors','article','img'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(ArticleRequest $request)
    {
        $requestData = $request->all();

        if(!Auth::user()->hasRole(User::AUTHOR_ROLE))
        {
            $requestData['verified']    = true;
            $requestData['verified_by'] = Auth::user()->id;
        }

        $requestData['created_by'] = Auth::user()->id;

        if(isset($requestData['sub_category_id']))
        {
            $requestData['category_id'] = $requestData['sub_category_id'];
        }
        $article   = Article::create($requestData);
        if($request->hasFile('article_image'))
        {
            $article->addMedia($request->article_image)
            ->toMediaCollection('article_coll');
        }

        $tags      = $request->tags;
        $splitTags = explode(',',$tags);
        foreach($splitTags as  $splitTag )
        {
            $tagsTable = Tag::where('name',$splitTag)->first();
            if($tagsTable == null)
            {
                $tagsTable        = new Tag();
                $tagsTable->name  = $splitTag;
                $tagsTable->save();
            }

            $tagsArticleTable             = new ArticleTag();
            $tagsArticleTable->article_id = $article->id;
            $tagsArticleTable->tag_id     = $tagsTable->id;
            $tagsArticleTable->save();
        }
        $article->refreshSlug();

        if ($article->save())
        {
            \SEO\Seo::save($article, route('article.single', $article->slug), [
                    'title' => $article->title,
                    'images' => [
                    $article->cover_photo
                ]
            ]);
        }
        return redirect()->route('dashboard.article.index')->withSuccess('Success','تمت الاضافة بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show(Article $article)
    {
        return view('dashboard.article.single',compact('article'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Article $article)
    {
        $categories = Category::parents()->get();
        $authors    = User::all();
        $media      = $article->getMedia('article_coll')->first();
        $img        = $media ? $media->getFullUrl() : '';
        $tags       = ArticleTag::where('article_id',$article->id)->get();
        return view('dashboard.article.form',compact('categories','authors','article','img','tags'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(ArticleRequest $request, Article $article)
    {
        $requestData = $request->all();

        if(isset($requestData['sub_category_id']))
        {
            $requestData['category_id'] = $requestData['sub_category_id'];
        }

        $article->update($requestData);

        if($request->article_image != null)
        {
            $article->addMedia($request->article_image)
                    ->toMediaCollection('article_coll');
        }
        $article->refreshSlug();

        if ($article->save())
        {
            \SEO\Seo::save($article, route('article.single', $article->slug), [
                    'title' => $article->title,
                    'images' => [
                    $article->cover_photo
                ]
            ]);
       }
        return redirect()->route('dashboard.article.index')->withSuccess('Success','تمت التعديل بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy(Article $article)
    {
        $article->delete();
        return redirect()->route('dashboard.article.index')->withSuccess('تم حذف المقال بنجاح');
    }

    public function saveArticle(Request $request,$article)
    {
        $article = Article::find($article);
        $article->update
            ([
                'is_news'=> $request->is_news,
                'is_important'=> $request->is_important ,
                'in_slider'=> $request->is_slider ,
                'is_infographic'=> $request->is_infographic,
                'is_author' => $request->is_author
            ]);
        return back()->withSuccess('تم التعديل بنجاح');
    }

    public function addToTrend(Request $request)
    {
        $trend = Trend::find($request->trend_id);
        $articles = $request->articles;
        $trend->articles()->attach($articles);
        return response()->json(['message'=>'تم اضافة المقالات الى الترند بنجاح']);
    }

    public function verify(Article $article)
    {
        $article->update([
            'verified'=>true,
            'verified_by'=> Auth::user()->id
        ]);
        return back()->withSuccess('تم الموافقة على المقالة بنجاح');
    }

}

app/Http/Controllers/Dashboard/CategoriesController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use App\Http\Requests\CategoryRequest;
use App\Models\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    public function __construct()
    {
        $this->middleware(['role:Super Admin']);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::paginate(20);
        return view('dashboard.categories.index',compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $parentCategories = Category::parents()->get();
        $category = new Category();
        return view('dashboard.categories.form',compact('parentCategories','category'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CategoryRequest $request)
    {
        $category = Category::create($request->all());
        $category->refreshSlug();
        return redirect()->route('dashboard.categories.index')->withSuccess('Success','تمت اضافة القسم بنجاح');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        $parentCategories = Category::parents()->get();
        return view('dashboard.categories.form',compact('category','parentCategories'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(CategoryRequest $request,Category $category)
    {
        $category->update($request->all());
        $category->refreshSlug();
        return back()->withSuccess('تم تعديل القسم بنجاح');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  Category  $cateogry
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        $category->delete();
        return back()->withSuccess('تم الحذف بنجاح');
    }

    public function getChildren(Category $category)
    {
        if($category->children()->count())
        {
            $children = $category->children;
            return response()->json($children);
        }
        else
        {
            return 'false';
        }
    }

    public function orderIndex()
    {
        $homeCategories = Category::where('in_homepage',1)->orderBy('homepage_order','ASC')->get();
        $notHomeCategories = Category::where('in_homepage',0)->get();
        return view('dashboard.categories.order-categories',compact('homeCategories','notHomeCategories'));
    }

    public function orderSubmit(Request $request)
    {
        $sortingArr = $request->sortingArr;
        Category::query()->update([
            "in_homepage" => 0
        ]);
        foreach ($sortingArr as $index => $category_id) 
        {
            $category = Category::find($category_id);

            $category->update([
                "in_homepage"=>'1',
                "homepage_order"=>$index
            ]);    
        }

        return "success";
    }
}

app/Http/Controllers/Dashboard/HomeController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Models\Article;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Carbon\Carbon;
use Sarfraznawaz2005\VisitLog\Models\VisitLog;

class HomeController extends Controller
{
    /**
     * Return Dashboard Homepage
     */
    public function home(Request $request)
    {
        $articlesCount = Article::count();
        $unVerifiedAriclesCount = Article::where('verified',false)->count();
        $topTenArticles = Article::orderBy('visits','desc')->take(10)->get(); 
        $lastMonthVisits = VisitLog::where('created_at','>=',Carbon::now()->subMonth()->firstOfMonth())->count();
        $monthVisits = VisitLog::where('created_at','>=',Carbon::now()->firstOfMonth())->count();
        $chartDaysVisits = $this->getDaysVisitsArray(7);
        // dd($chartDaysVisits); 
        return view('dashboard.home',compact(
            'articlesCount',
            'unVerifiedAriclesCount',
            'lastMonthVisits',
            'monthVisits',
            'chartDaysVisits',
            'topTenArticles'
        ));
    }

    public function getDaysVisitsArray($daysNum)
    {
        $date = Carbon::now()->subDays($daysNum);

        $days = array();
        $daysLabels = array();
        $visits = array();
        for($i=0 ; $i<$daysNum+1 ; $i++)
        {
            array_push($daysLabels,$date->format('M-d'));
            // $dayVisitors = VisitLog::whereBetween('created_at',[$date->toDateTimeString(),$date->addDay()->toDayDateTimeString()])->count();
            $dayVisitors = VisitLog::whereDate('created_at',$date)->count();
            $date->addDay();
            array_push($days,$i+1);
            array_push($visits,$dayVisitors);
        }
        $days = json_encode($days);
        // dd(Carbon::now()->toDateTimeString());
        // dd(VisitLog::whereDate('created_at',Carbon::now())->count());
        $visits = json_encode($visits);
        // $visitsCount = VisitLog::count();
        $daysLabels = json_encode($daysLabels);

        return [
            'days' => $daysLabels,
            'visits' => $visits
        ];
    }
}

app/Http/Controllers/Dashboard/ImageController.php
<?php

namespace App\Http\Controllers\Dashboard;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Storage;

class ImageController extends Controller
{
    public function editorUpload(Request $request)
    {
        $file = $request->upload->store('/public');
        $fileUrl = Storage::url($file);
        $fileName = basename($file);
        $response = [
            'fileName' => $fileName,
            'uploaded' => 1,
            'url' => $fileUrl,
        ];
        return response()->json($response);
    }
}

resources/views/dashboard/layouts/form_scripts.blade.php
<script src="{{asset('dashboard-assets/js/form_elements.js')}}" type="text/javascript"></script>
<script src="{{asset('dashboard-assets/js/scripts.js')}}" type="text/javascript"></script>

resources/views/dashboard/layouts/main.blade.php
<!DOCTYPE html>
<html dir="rtl">
    <head>
        @include('dashboard.layouts.head')
    </head>
    <body class="fixed-header dashboard">
        @include('dashboard.layouts.sidebar')
        <!-- START PAGE-CONTAINER -->
        <div class="page-container">
            @include('dashboard.layouts.header')
            <!-- START PAGE CONTENT WRAPPER -->
            <div class="page-content-wrapper">
                @yield('content')
            </div>
            <!-- END PAGE CONTENT WRAPPER -->

        </div>
        <!-- END PAGE CONTAINER -->
        @include('dashboard.layouts.scripts')
        @include('dashboard.layouts.sweetalert')
        @yield('javascript')
    </body>
</html>

resources/views/dashboard/layouts/sidebar.blade.php
<!-- BEGIN SIDEBPANEL-->
<nav class="page-sidebar" data-pages="sidebar">

    <!-- BEGIN SIDEBAR MENU HEADER-->
    <div class="sidebar-header">
        <a">
            <img src="{{asset('site/images/icons/logo-02.png')}}" alt="logo" class="brand"
            data-src="{{asset('site/images/icons/logo-02.png')}}" data-src-retina="{{asset('site/images/icons/logo-02.png')}}"
            style="height: 75%; width: 80px; object-fit: contain;">
        </a>
        <button type="button" class="btn btn-link visible-lg-inline" data-toggle-pin="sidebar">
            <i class="fa fs-12"></i>
        </button>
    </div>
    <!-- END SIDEBAR MENU HEADER-->

    <!-- START SIDEBAR MENU -->
    <div class="sidebar-menu">
        <!-- BEGIN SIDEBAR MENU ITEMS-->
        <ul class="menu-items">
            <li class="m-t-30 open">
                <a href="{{route('dashboard.home')}}" class="detailed">
                    <span class="title">الصفحة الرئيسية</span>
                </a>
                <span class="icon-thumbnail bg-success"><i class="pg-home"></i></span>
            </li>

            {{-- <li class="">
                <a href="javascript:;"><span class="title"> بيانات الصفحة الرئيسية </span>
                <span class=" arrow"></span></a>
                <span class="icon-thumbnail"><i class="pg-layouts"></i></span>
                <ul class="sub-menu">
                    <li class="">
                        <a href="#">بيانات الصفحة الرئيسية </a>
                        <span class="icon-thumbnail">H</span>
                    </li>
                </ul>
            </li> --}}

            {{-- <li class="">
                <a href="javascript:;"><span class="title">النظرة الفنية</span>
                <span class=" arrow"></span></a>
                <span class="icon-thumbnail"><i class="pg-layouts"></i></span>
                <ul class="sub-menu">
                    <li class="">
                        <a href="#">مقالات النظرة الفنية</a>
                        <span class="icon-thumbnail">P</span>
                    </li>
                    <li class="">
                        <a href="#">اضافة مقال</a>
                        <span class="icon-thumbnail">+</span>
                    </li>
                </ul>
            </li> --}}
            @if (auth()->user()->hasRole('Super Admin'))
            <li class="">
                <a href="javascript:;"><span class="title"> المستخدمين </span>
                <span class=" arrow"></span></a>
                <span class="icon-thumbnail"><i class="pg-layouts"></i></span>
                <ul class="sub-menu">
                    <li class="">
                        <a href="{{route('dashboard.users.index')}}">المستخدمين</a>
                        {{-- <span class="icon-thumbnail">P</span> --}}
                    </li>
                    <li class="">
                        <a href="{{route('dashboard.users.create')}}">اضافة مستخدم</a>
                        {{-- <span class="icon-thumbnail">P</span> --}}
                    </li>

                </ul>
            </li>
            @endif
            <li class="">
                <a href="{{route('dashboard.users.edit',auth()->user()->id)}}" class="detailed">
                    <span class="title">
                        حسابى
                    </span>
                </a>
                <span class="icon-thumbnail"><i class="pg-layouts"></i></span>
            </li>
            @if (auth()->user()->hasRole('Super Admin'))
            <li class="">
                <a href="javascript:;"><span class="title"> الاقسام </span>
                <span class=" arrow"></span></a>
                <span class="icon-thumbnail"><i class="pg-layouts"></i></span>
                <ul class="sub-menu">
                    <li class="">
                        <a href="{{route('dashboard.categories.index')}}">الاقسام</a>
                        {{-- <span class="icon-thumbnail">P</span> --}}
                    </li>
                    <li class="">
                        <a href="{{route('dashboard.categories.order')}}">التحكم فى اقسام الصفحة الرئيسية</a>
                        {{-- <span class="icon-thumbnail">P</span> --}}
                    </li>
                    <li class="">
                        <a href="{{route('dashboard.categories.create')}}">اضافة قسم</a>
                        {{-- <span class="icon-thumbnail">P</span> --}}
                    </li>

                </ul>
            </li>
            @endif
            <li class="">
                <a href="javascript:;"><span class="title"> المقالات </span>
                <span class=" arrow"></span></a>
                <span class="icon-thumbnail"><i class="pg-layouts"></i></span>
                <ul class="sub-menu">
                    <li class="">
                        <a href="{{route('dashboard.article.index')}}">المقالات</a>
                        <span class="icon-thumbnail">A</span>
                    </li>
                    <li class="">
                        <a href="{{route('dashboard.article.create')}}">اضافه مقال</a>
                        <span class="icon-thumbnail">+</span>
                    </li>

                </ul>
            </li>
            @if (auth()->user()->hasRole('Super Admin'))
            <li class="">
                <a href="javascript:;"><span class="title"> الموقع </span>
                <span class=" arrow"></span></a>
                <span class="icon-thumbnail"><i class="pg-layouts"></i></span>
                <ul class="sub-menu">
                    <li>
                        <a href="{{route('dashboard.about.create')}}">عن الموقع</a>
                        <span class="icon-thumbnail">A</span>
                    </li>
                    <li>
                        <a href="{{route('__visitlog__')}}">زيارات الموقع</a>
                        <span class="icon-thumbnail">A</span>
                    </li>
                </ul>
            </li>
            @endif
            <li class="">
                <a href="{{route('dashboard.subscribtion.index')}}" class="detailed">
                    <span class="title"> المشتركين </span></a>
                <span class="icon-thumbnail"><i class="pg-layouts"></i></span>

            </li>
            @if (auth()->user()->hasRole(['Super Admin','Moderator']))

            <li class="">
                <a href="javascript:;"><span class="title"> التريندات </span>
                <span class=" arrow"></span></a>
                <span class="icon-thumbnail"><i class="pg-layouts"></i></span>
                <ul class="sub-menu">
                    <li class="">
                        <a href="{{route('dashboard.trend.index')}}">التريندات</a>
                        <span class="icon-thumbnail">A</span>
                    </li>
                    <li class="">
                        <a href="{{route('dashboard.trend.create')}}">اضافه تريند</a>
                        <span class="icon-thumbnail">+</span>
                    </li>
                </ul>
            </li>
            @endif
        </ul>
        <div class="clearfix"></div>
    </div>
    <!-- END SIDEBAR MENU -->

</nav>
<!-- END SIDEBAR -->
<!-- END SIDEBPANEL-->

resources/views/dashboard/layouts/sweetalert.blade.php
@if($errors->any())
<script>
	swal({
		title: 'بالرجاء ادخال البيانات صحيحة',
		html: '{!! implode('<br>',$errors->all()) !!}',
		type: 'error'
	})
</script> 
@endif

@if (session('success'))
<script>
	swal({
		title: 'تم بنجاح',
		html: '{{ session('success') }}',
		type: 'success'
	})
</script>
@elseif (session('error'))
	<script>
        swal({
            title: 'خطأ',
            html: '{{ session('error') }}',
            type: 'error'
        })
	</script>
@endif
@if(auth()->user()->delete_requested)
	<script>
		swal({
			title: "تم طلب حذف حسابك",
			text: "تم طلب حذف حسابك من سوبر ادمن هل انت موافق؟",
			type: "warning",
			showCancelButton: true,
			cancelButtonText: "لا",
			confirmButtonColor: "#DD6B55",
			confirmButtonText: "نعم, اريد الحذف"
		}).then(result => {
			$.post('{{route('dashboard.users.confirmDelete')}}',
			{
				_token : '{{csrf_token()}}',
				value : result.value
			},function(response){
				// console.log(response);
				
				if (response == 'true') 
				{
					// console.log('true');
					
					location.reload();
				}
				else
				{
					
				}
			});
		});
	</script>
@endif
<script>
	$('button').parent('form:has(input[value="DELETE"]):not(".no-confirm")').click(function( e ) {
		e.preventDefault();
		var form = $(this).parents('form');
		swal({
			title: "هل تريد الحذف؟",
			text: "لا يمكن الرجوع فى الحذف",
			type: "warning",
			showCancelButton: true,
			cancelButtonText: "لا",
			confirmButtonColor: "#DD6B55",
			confirmButtonText: "نعم, اريد الحذف"
		}).then(result => {
			if (result.value) $(this).submit();
		});
	});
</script>